uni_test/klass/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

urlpatterns = [
        path('', views.main , name='main'),
        path('login', views.login , name = 'login'),
        path('logout', views.logout_view , name='logout'),
        path('register' , views.register , name = 'register'),
       # path('ajax/validate_username/', views.validate_username, name='validate_username'),
        path('add_kurse' , views.add_kurse , name = 'add_kurse'),
        path('change_pass' , views.change_pass , name = 'change_pass'),
        path('change user', views.change_user , name = 'change_user'),
        path('change_email' , views.change_email , name = 'change_email') ,
        path('chat' , views.chat_view , name = 'chat') ,
        path('chat/<int:pk>' , views.chat_view_thread , name='chat_thread'),
        path('add_lektion/<int:pk>' , views.add_lektion , name = 'add_lektion'),
        path('remove_lektion/<int:pk>' , views.remove_lektion , name = 'remove_lektion'),
        path('add_comment' , views.add_comment , name = 'add_comment'),
        path('remove_comment/<int:pk>' , views.remove_comment , name= 'remove_comment'),
        path('show_comment/<int:pk>'  , views.show_comment , name  = 'show_comment'),
        path('search' , views.search , name = 'search' ),
        path('make_follow/<int:pk>' , views.make_follow , name = 'make_follow'),
        ]

uni_test/klass/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser
from datetime import datetime


# Create your models here.

class User(AbstractUser):
    """

    """
    location = models.CharField(max_length=30, blank=True)
    phone_number = models.CharField( max_length=13, blank=True)
    bio = models.CharField(blank= True,max_length=100) 
    photo = models.ImageField(blank = True)


class Kurse(models.Model):
    """
    main table for klasses
    just need to finde a way to performe video and text and other stuff

    """

    auther = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length = 20 , help_text = "Name of the klass")
    create_date = models.DateTimeField(auto_now_add = True)
    chang_date = models.DateTimeField(auto_now = True)
    photo = models.ImageField(blank = True)
    
    def __str__(self):
        return '{} by {}'.format(self.name , self.auther)
    class Meta:
        ordering = ["-chang_date"]


class Lektion(models.Model):
    """
    every kurs has many lektionen
    """
    name = models.CharField(blank = True , max_length = 20) 
    auther = models.ForeignKey(User , on_delete = models.CASCADE)
    text = models.TextField()
    media = models.FileField(blank = True)
    kurse = models.ForeignKey(Kurse , on_delete = models.CASCADE)
    mod_date = models.DateTimeField(auto_now_add = True)
    chang_date = models.DateTimeField(auto_now = True)


    def __str__(self):
        return '{} of {}'.format(self.name , self.kurse)
    class Meta:
        ordering = ["chang_date"]

    
class Comment(models.Model):
    """
    table for store and use comments
    nothing to do 
    """

    lektion = models.ForeignKey(Lektion , on_delete = models.CASCADE ) 
    auther = models.ForeignKey(User , on_delete = models.CASCADE)
    text = models.CharField(max_length=200)
    kurse = models.ForeignKey(Kurse , on_delete = models.CASCADE)
    create_date = models.DateTimeField(auto_now_add = True)
    chang_date = models.DateTimeField(auto_now = True)
    show = models.BooleanField(default = False)


    def __str__(self):
        return 'Comment by {} on {}'.format(self.auther,self.kurse)
    
    class Meta:
        ordering = ["chang_date"]



class Followe_Kurse(models.Model):
    """
    make 1 V 1 relation between user and followed kurse
    """

    user = models.ForeignKey(User , on_delete = models.CASCADE)
    kurse = models.ForeignKey(Kurse , on_delete = models.CASCADE)

uni_test/klass/views.py
from django.http import HttpResponseForbidden ,HttpRequest
from django.contrib.auth import authenticate , logout , login as a_login
from .models import User , Comment , Kurse , Lektion,Followe_Kurse
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .helper import ajax_required
from django.views.decorators.http import require_http_methods
import re
from datetime import datetime

# Create your views here.



def main(request):
    return render(request ,'main.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            a_login(request,user)
            return redirect('chat')
        return render(request,'login.html',{'error':True,})

    else:
        return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('/')



def register(request):
    if request.method == 'POST':
        try:
            new_user= User.objects.get(username= request.POST["username"])
        except User.DoesNotExist:
            #check if username and password field correctly

            if ( request.POST['password'] == request.POST['passwordRepeat']):
                new_user = User(username = request.POST['username'],)
                new_user.set_password(request.POST["password"])
                new_user.save()
                return redirect('login')
            else:
                return render(request , 'register.html',{'errorpass':True})
                
        else:
            return render(request , 'register.html',{'erroruser':True})
    else:
        return render(request , 'register.html')


@login_required
def profile(request):
    return render(request , 'profile.html')

@login_required
def change_user(request):
    if request.method == 'POST':
        c_user = get_object_or_404(User  , request.user )
        c_user.username = request.POST['newUser']
        c_user.save()
        return render(request ,'profile.html')

@login_required
def change_pass(request):
    if request.method == 'POST':
        c_user = get_object_or_404(User , request.user)
        c_user.set_password(request.POST['changeInputChild'])
        c_user.save()
        logout(request)
        return redirecrt("login")  
    
@login_required
def change_email(request):
    if request.method == 'POST':
        c_user = get_object_or_404(User , request.user)
        userEmail = re.match(r"^.+@.+\..+$" , request.POST['changeInputChild'])
        if userEmail:
            userEmail = request.POST['changeInputChild']
        else:
            userEmail = ''
        c_user.email = userEmail
        c_user.save()
        return render(request , 'profile.html')

@login_required
def chat_view(request):
    kurses = list(Kurse.objects.filter(auther = request.user))
    FollowedByUser = Followe_Kurse.objects.filter(user = request.user)
    for relation in FollowedByUser:
        kurses.append(relation.kurse)
    kurses.sort(key=lambda x: x.chang_date ,reverse = True )
    return render(request , 'chat.html',{'kurses':kurses})

@login_required
def chat_view_thread(request, pk):
    if request.method == 'GET':
        c_kurse = get_object_or_404(Kurse , id=pk)
        kurses = list(Kurse.objects.filter(auther = request.user))
        FollowedByUser = Followe_Kurse.objects.filter(user = request.user)
        for relation in FollowedByUser:
            kurses.append(relation.kurse)
        kurses.sort(key=lambda x: x.chang_date , reverse = True )
        is_followed = False
        is_admin = False
        if c_kurse.auther == request.user:
            is_admin = True
        if c_kurse in kurses:
            is_followed = True
        return render(request , 'chat_thread.html' , {'c_kurse':c_kurse,'kurses':kurses,'is_admin':is_admin,'is_followed':is_followed})
    else:
        return HttpResponseForbidden()


@login_required
def add_lektion(request , pk):
    if request.method == 'POST':
        c_kurse = get_object_or_404(Kurse , id=pk)
        if c_kurse.auther == request.user:
            new_lektion = Lektion(auther = request.user , text = request.POST['content'] ,kurse = c_kurse  )
            new_lektion.save()
            c_kurse.chang_date = datetime.now()
            c_kurse.save()
            return redirect("chat_thread" , pk)
        else:
            return HttpResponseForbidden()
    else:
        return HttpResponseForbidden()

@login_required
def add_comment(request ,):
    if request.method == 'POST':
        if 'lektion_radio'  not in request.POST:
            return redirect('chat')
        pk = request.POST['lektion_radio']
        c_lektion = get_object_or_404(Lektion , id = pk)
        new_comment = Comment(lektion = c_lektion , auther = request.user , text = request.POST['content'] , kurse = c_lektion.kurse )
        new_comment.save()
        return redirect("chat_thread" , c_lektion.kurse.id)
    else:
        return HttpResponseForbidden()  


@login_required
def  show_comment(request , pk):
    c_comment = get_object_or_404(Comment , id = pk)
    kurse = c_comment.kurse
    print("salam")
    print(request.user)
    print(kurse.auther)
    if request.user == kurse.auther or request.user == c_comment.auther:
        c_comment.show = not c_comment.show
        c_comment.save()
        return redirect("chat_thread" , kurse.id)

    else: 
        return HttpResponseForbidden()  



@login_required
def remove_comment(request , pk):
    c_comment = get_object_or_404(Comment , id = pk)
    kurse = c_comment.kurse
    if request.user == kurse.auther or request.user == c_comment.auther:
        c_comment.delete()
        return redirect("chat_thread" , kurse.id)

    else: 
        return HttpResponseForbidden()  


  
@login_required
def add_kurse(request):
    if request.method == 'POST':
        new_kurse = Kurse(auther = request.user , name = request.POST['name'])
        new_kurse.save()
        return redirect("chat_thread" , new_kurse.id)
    else:
        return render(request ,'add_kurse.html')

@login_required
def remove_lektion(request , pk):
    c_lektion = get_object_or_404(Lektion , id = pk)
    kurse = c_lektion.kurse
    if request.user == kurse.auther:
        c_lektion.delete()
        return redirect("chat_thread", kurse.id)
    else:
        return HttpResponseForbidden()


def search(request):
    if request.method == 'POST':
        empty = False
        resault = Kurse.objects.filter(name__icontains= request.POST['search'])
        if not resault:
            empty = True
        return render(request , 'search.html',{'resault':resault , 'empty':empty})
    else:
        return render(request , 'search.html')

@login_required
def make_follow(request , pk):
    c_kurse = get_object_or_404(Kurse  , id = pk)
    relation = Followe_Kurse.objects.get_or_create(user = request.user ,kurse = c_kurse)
    return redirect("chat_thread" , c_kurse.id)

uni_test/klass/templates/.base.html
{% load static %}<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.rawgit.com/rastikerdar/vazir-font/v19.0.0/dist/font-face.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
   {% block stylesheet %}{% endblock %}
  <title>LogIn</title>
</head>
<body>




	{% block content %}{% endblock %}







    <footer>
      <div class="sideFooter">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi voluptate voluptatum corrupti reprehenderit pariatur quae asperiores soluta in deleniti id.</p>
        </div>
      <div class="linkListParent">
        <ul>
          <li><a class="listLink" href="#">خانه</a></li>
          <li><a class="listLink" href="#">فرصت شغلی</a></li>
          <li><a class="listLink" href="#">مدیران</a></li>
          <li><a class="listLink" href="#">تولید کنندگان</a></li>
          <li><a class="listLink" href="#">لیست تمام دروس</a></li>
        </ul>
      </div>
    </footer>
  </div>
    {% block modal %}{% endblock modal %}
</body>
</html>

uni_test/klass/templates/.base_profile.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <link href="https://cdn.rawgit.com/rastikerdar/vazir-font/v19.0.0/dist/font-face.css" rel="stylesheet" type="text/css" />

  <title>Profile Page</title>
</head>
<body>
  <div class="wrapper">
    <div class="header headerProfile">
      <p>پروفایل</p>
      <i class="bars fas fa-bars"></i>
      <i class="cross fas fa-times"></i>
    </div>


        {% block content %}{% endblock %}







    <footer>
      <div class="sideFooter">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
      </div>
      <div class="linkListParent">
        <ul>
          <li><a class="listLink" href="#">خانه</a></li>
          <li><a class="listLink" href="#">فرصت شغلی</a></li>
          <li><a class="listLink" href="#">مدیران</a></li>
          <li><a class="listLink" href="#">تولید کنندگان</a></li>
          <li><a class="listLink" href="#">لیست تمام دروس</a></li>
        </ul>
      </div>
    </footer>
  </div> <!-- End Of Wrapper -->
      {% block modal %}{% endblock modal %}
</body>
</html>

uni_test/klass/templates/.chat_thread.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <link href="https://cdn.rawgit.com/rastikerdar/vazir-font/v19.0.0/dist/font-face.css" rel="stylesheet" type="text/css" />
  <title>THREADS WITH CONTENTS INCLUDED</title>
</head>
<body>
  <!--WRAPPER STARTS HERE-->  
  <div class="chatWrapper">
    <!--HEADER STARTS HERE-->
    <div class="chatHeader">
      
      <!--SETTING MENU BUTTON STARTS HERE-->
      <div class="settingMenuButton">
        <i class="settingButton fas fa-ellipsis-v"></i>
      </div>
      <!--SETTING MENU BUTTON ENDS HERE-->
      
      <!--NOTIFICATION BELL ICON STARTS HERE-->
      <div class="notification">
        <i class="fas fa-bell"></i>
      </div>
      <!--NOTIFICATION BELL ICON ENDS HERE-->
      
      <!--SLOGAN STARTS HERE-->
      <div class="slogan">
        <p class="sloganP">به دانا خوش آمدید</p>
      </div>
      <!--SLOGAN ENDS HERE-->
      <!--PURCHASE BUTTON STARTS HERE-->
      <div class="purchaseButton">
        <button class="purchase">
          <i class="fas fa-shopping-cart"><span class="shoppingMessage">عضویت</span></i>
        </button>
      </div>
      <!--PURCHASE BUTTON ENDS HERE-->
    </div>
    <!--HEADER ENDS HERE-->
    <div class="chatContentWrapper">
      <!--SETTING STARTS HERE-->
      <div class="settingWrapper">
      
        <!--SETTING HEADER STARTS HERE-->
        <div class="settingHeader">
      
          <!--USER IMAGE HOLDER STARTS HERE-->
          <div class="headerContentHolder">
            <div class="userIdAndImage">
              <figure class="userImage">
		      <img class="imageOfUser" src="{% static 'images/img_avatar.png' %}" alt="user image">
              </figure>
	      <p class="userId">{{ user.username }}</p>
	      <p class="userNameSetting">@{{ user.username }}</p>
            </div>
            <!--USER IMAGE HOLDER ENDS HERE-->
      
            <!--USER IMAGE CHANGER BUTTON STARTS HERE-->
            <div class="imageChanger">
              <i class="fas fa-camera"></i>
            </div>
          </div>
          <!--USER IMAGE CHANGER BUTTON ENDS HERE-->
        </div>
        <!--SETTING HEADER ENDS HERE-->

        <!--SETTING LIST STARTS HERE-->
        <div class="settingList">
          <ul class="settingListHolder">
            <li class="settingListChilderen">دروس من</li>
            <li class="settingListChilderen">دروس ثبت نام کرده</li>
            <li class="settingListChilderen">پروفایل</li>
            <li class="settingListChilderen">خروج</li>
            <li class="settingListChilderen">لیست کلیه دوره های موجود</li>
          </ul>
        </div>
        <!--SETTING LIST ENDS HERE-->

      </div>
      <!--SETTING ENDS HERE-->


      <!--SIDE THREAD VIEW STARTS HERE-->
      <div class="sideThreadView">

        <!--SIDE VIEW SEARCH STARTS HERE-->
        <div class="sideHeaderChat">
        
          <!--SIDE SEARCH FORM STARTS HERE-->
          <form action="#" class="sideSearch">
            <input class="sideSearchInput" type="text"placeholder="دروس مورد نظر خود را جستجو کنید">
            <button class="sideSearchButton">
              <i class="fas fa-search"></i>
            </button>
          </form>
          <!--SIDE SEARCH FORM ENDS HERE-->
        </div>
        <!--SIDE VIEW SEARCH ENDS HERE-->
      
      
        <!--THE ACTUAL THREADS STARTS HERE-->
        <div class="actualThreadsWrapper">
        
		{% for kurse in kurses %}
          <!--SAMPLE THREADS START HERE-->
	  <a class="classLink" href="{% url 'chat_thread' kurse.id %}">
          <div class="thread threadOne">
            <figure class="userImageHolder">
		    <img class="UserThreadImage" src="{% static 'images/img_avatar.png' %}" alt="user image">
            </figure>
            <div class="threaInfos">
		    <p class="userNameForThreads">{{ kurse.name }}</p>
		    <p class="lessonBriefForThreads">{{ kurse.name }} is hier</p>
            </div>
          </div>
          </a>

	  {% endfor %}
            <!--SAMPLE THREADS END HERE-->
      
      
        </div>
        <!--THE ACTUAL THREADS ENDS HERE-->
    
      </div>
    
    
      <!--THE PLUSE SIGN GOES HERE FOLKS-->
      <!-- <div class="adder">
        <i class="fas fa-plus-circle"></i>
      </div> -->
      <!--THE PLUSE SIGN ENDS HERE FOLKS-->
    
    
      <!--SIDE THREAD VIEW ENDS HERE-->
  
    
    
      <!--CHAT VIEWER CONTENT GOES HERE-->
      <div class="chatWrapperLeft">
      
      
      <!--FOR THE NEXT TEMPLATE YOU SHOULD DELETE THIS PART-->
        <div class="contentViewer">
          <div class="crossCircle">
            <i class="far fa-times-circle"></i>
          </div>


	  {% for lektion in c_kurse.lektion_set.all %}

          <!--SAMPLE CONTENT FOR CHAT VIEWER STARTS HERE-->
          <div class="classPart">
            <p class="sampleLesson">
	    {{ lektion.text }} 
            </p>
        </div>
        <!--THIS IS THE ACARDION PART (STARS HERE)-->
        <div class="acardion">
          <button class="showMore">
            <i class="fas fa-angle-double-down"></i>
            
          </button>
          <p class="commentDescription">نظرات درس یک</p>
        </div>
        <div class="comments">
	{% for comment in lektion.comment_set.all %}
          <div class="comentChildren">
		  <p class="commentP">{{ comment.text}}</p>
            <div class="viewToggle"> 
		{% if is_admin %}
              <div class="toggleOff"><i class="fas fa-toggle-off"></i></div>
	      	{% endif %}
            </div>
          </div>
	  {% endfor %}
          <div class="commentForm">
	    <form action="{% url 'add_comment' lektion.id %}"  method="post" class="commentHolder">
		{% csrf_token %}
              <input type="text" name="comment" class="commentInput" placeholder="نظر خود را با ما به اشتراگ گزارید">
              <button class="commentButton">ثبت نظر</button>
            </form>
          </div>
        </div>
        <!--THIS IS THE ACARDION PART (ENDS HERE)-->
      
	{% endfor %}

	{% if is_admin %}
         <!--THIS PART MUST GET DELETED AS WELL BUDDY-->
      <div class="chatInputHolder">
	      <form  method="POST" action="{% url 'add_lektion' c_kurse.id %}" class="chatForm">
		      {% csrf_token %}
          <input class="chatInput" name="lektion" type="text" placeholder="مطلب مورد نظر خود را وارد نمایید">
          <button class="chatSenderButton">
            <i class="far fa-paper-plane"></i>
          </button>
        </form>
      </div>
      {% endif %}
      <!--THIS PART MUST GET DELETED AS WELL BUDDY-->
      <!--SAMPLE CONTENT FOR CHAT VIEWER ENDS HERE-->
      </div>

      <!--FOR THE NEXT TEMPLATE YOU SHOULD DELETE THIS PART-->
      
      
     

      </div>
    </div>
    <!--CHAT VIEWER CONTENT ENDS HERE-->
  </div>
  <!--WRAPPER ENDS HERE-->


  <div class="modal"> <!--WIDTH AND HEIGHT 100VH/VW-->
    <div class="popUp"> <!--THE ACTUAL CONTENT GOES IN HERE AND THIS IS THE MODAL-->
      <div class="popUpHeader">
        <div class="closeIt">
          <i class="far fa-times-circle"></i>
        </div>
        <p class="popUpMessage">برای ثبت نام دوره لطفا اطلاعات خود را وارد نمایید</p>
      </div>
      <div class="bankAPIButton">
        <button class="bank">ورود به سامانه بانک</button>
      </div>
    </div>
  </div>
  <script src="{% static 'js/chat.js'%}"></script>
</body>
</html>

uni_test/klass/templates/.login.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
    <div class="header">
      <p>ورود</p>
    </div>
    
    <div class="registerForm">
	<form class="registrationForm" method="post" action="{% url 'login' %}">
	{% csrf_token %}
        <input class="userName" type="text" name="userName" placeholder="username">:نام کاربری
        <input class="userPassword" type="text" name="userPassword">:کلمه عبور
        <input class="registerButton" id="generalButtonID" type="submit" value="ورود">
      </form>
      {% if  error  %}
	<p> etwas ist falsch </p>
      {% endif %}
    </div>
{% endblock %}

uni_test/klass/templates/.main.html
{% extends "base.html" %}

{% block content %}

  <div class="wrapper">
    <div class="header">
      <p>خانه</p>
    </div>
    <div class="mainPageContent">
      <div class="entranceMessage">
        <p>به سامانه یک پارچه <span>دانا</span> خوش آمدید</p>
      </div>
      <div action="#" class="entrance">
	      <a class="button enterViaNumber" href={% url "login" %}><button class="button enterViaNumber" type="button" name="enterViaNumber">ورورد با شماره همراه</button></a>
	      <a class="button enterViaEmail" href={% url "login"%}><button class="button enterViaEmail" type="button" name="enterViaEmail" >ورود با پست الکترونیکی</button></a>
	      <a class="button newUser" href={% url "register" %}><button class="button newUser" type="button" name="newUser">ثبت نام</button></a>
      </div>  
    </div>
{% endblock %}

uni_test/klass/templates/.register.html
{% extends "base.html" %}
{% load staticfiles%}

{% block content %}
<div class="wrapper">
    <div class="header">
        

      <p>ثبت نام</p>
    </div>
    <div class="registerForm">
	<form class="registrationForm" method="post" action="{% url 'register' %}">
	{% csrf_token %}	    
        <input class="firstName" type="text" name="firstName"><label class="firstNameLabel" for="firstName" placeholder="jj">:نام</label>
        <input class="familyName" type="text" name="familyName"><label class="familyNameLabel" for="familyName">:نام خانوادگی</label>
        <input class="userEmail" type="email" name="userEmail"><label class="userEmailLabel" for="userEmail">:پست الکترونیکی</label>
        <input class="userPhone" type="text" name="userPhone" ><label class="userPhoneLabel" for="userPhone">:تلفن همراه</label>
	<input class="userName" type="text" name="userName"><label class="userNameLabel" for="userName" id="id_username" >:نام کاربری</label>
        <input class="userPassword" type="password" name="userPassword"><label class="userPasswordLabel" for="userPassword">:کلمه عبور</label>
        <input class="userPasswordRepeat" type="password" name="userPasswordRepeat"><label class="userPasswordRepeatLabel" for="userPasswordRepeat">:تکرار کلمه عبور</label>
      <button class="registerButton" id="generalButtonID" type="submit">ثبت اطلاعات</button>
      </form>
    </div>



  
{% endblock %}

{% block modal %}
<script src="{% static 'js/globalSource.js' %}" type="text/javascript"></script>
{% endblock modal %}



uni_test/klass/templates/chat_thread.html
{% extends 'base.html' %} 



{% block content%}


<!-- Header -->
    <header class="masthead">
      <div class="container-fluid text-center">
      	<div class="row">
      

      	
      	
      	
      	
      	<div class="col-sm-9 col-xs-9 col-lg-9 col-md-9 tt">

 				<div class="card card--backg">
      			<form class="form-send" method="post" action="{% url 'add_comment'  %}">
			{% csrf_token %}
						<div class="col-sm-10 col-xs-10 col-lg-10 col-md-10">
          {% for lektion in c_kurse.lektion_set.all %}

							<div class="card--lg card--conten">
								<p>
								{{ lektion.text}}
								</p>
								{% if is_admin %}
								<a href="{% url 'remove_lektion' lektion.id %}"><i class="fa fa-trash text-danger"></i> </a>
								{% endif %}
							</div>
							<div class="col-md-1 col-lg-1 col-sm-1 col-xs-1 ">
								<input type="radio" name="lektion_radio" value="{{ lektion.id }}" />
							</div>
								<div class="col-sm-11 col-md-11 col-lg-11 col-xs-11">
						        {% for comment in lektion.comment_set.all %}
								{% if is_admin or comment.show or request.user == comment.auther %}
									<div class="card--lg card--content">
										<p>
										{{ comment.text }}
										</p>
										{% if is_admin %}
										<a href="{% url 'show_comment' comment.id %}"><i class="fa fa-eye fa-lg {% if comment.show %}text-success{% else%}text-danger{% endif %}"></i></a>
										<a href="{% url 'remove_comment' comment.id %}"><i class="fa fa-trash text-danger"></i> </a>
										{% endif %}
										{% if not comment.show and request.user == comment.auther %}
											<p class="text-danger" >در انتظار تایید مدرس</p>
										{% endif %}
									</div>	
								{% endif %}
							{% endfor %}
								</div>
	  {% endfor %}
						</div>
				</div>		
						
						
				<div class="form-row">
					<div class="input-group">
						{% if is_followed %}
  						<input type="text" class="form-control" name="content" placeholder="متن خود را وارد کنید ..." >
  						<div class="input-group-append">
    						<button class="btn btn-primary btn-outline-secondary"  type="submit">ارسال نظر</button>
						{% if is_admin%}<button class="btn btn-primary btn-outline-secondary"  type="submit" formaction="{% url 'add_lektion' c_kurse.id %}">ارسال درس</button>{% endif %}
  						</div>
						{% else %}
						<button class="btn btn-primary  btn-lg btn-primary btn-block" type="submit" formaction="{% url 'make_follow' c_kurse.id%}">دنبال کردن</button> 
						{% endif %}
					</div>
				</div>
      			</form>	 
      	</div>
      	
      	
   	
      	
      	
      	
      	
      	
      	
          <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3 sidean hidden-xs hidden-sm " >


	{% for kurse in kurses %}
	      <div class="card card--newsletter card--content">
		 <div class="row">
			 <a href="{% url 'chat_thread' kurse.id %}" >{{ kurse.name }} : {{ kurse.auther}}</a>
		</div>
	     </div>
	{% endfor %}


	  </div>
       </div>
      </div>

    </header>


   {% endblock %}